name: deltazx_authenticator
description: A simple Two-factor Authentication
version: 1.0.0
repository: https://github.com/patryyyy/deltazx_authenticator

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  otp: ^3.1.3
  args: ^2.4.0
  sm_crypto: ^1.0.3
  path: ^1.8.3
