import 'dart:io';

import 'package:path/path.dart';

import 'config/ini.dart';
import 'info/info.dart';
import 'info/path.dart';
import 'encrypt.dart';

class Account {
  Account([this._prefix]) {
    if (_prefix == null) {
      _prefix = join(Path.location, "config.ini");
    }
  }

  String? _prefix;
  String desc = "This file generated by dau, DO NOT EDIT.";

  void add(String name, String secret) {
    Ini config = Ini(_prefix!);
    if (config.hasKey(sectionName, name)) {
      stderr.writeln('ERROR: Account already exists.');
      exit(1);
    }

    config.set(sectionName, name, EncryptSecret.encodeData(secret));
    config.write(description: desc);
  }

  List<String> get accountList {
    Ini config = Ini(_prefix!);
    if (!config.hasSection(sectionName)) {
      stderr.writeln('ERROR: No such account.');
      exit(1);
    }
    return config.sectionItems(sectionName).keys.toList();
  }

  void delete(String name) {
    Ini config = Ini(_prefix!);
    if (!config.hasKey(sectionName, name)) {
      stderr.writeln('ERROR: No such account.');
      exit(1);
    }
    config.removeKey(sectionName, name);
    config.write(description: desc);
  }

  bool exist() {
    if (File(_prefix!).readAsStringSync().isEmpty) {
      return false;
    }
    Ini config = Ini(_prefix!);
    return config.sectionItems(sectionName).isNotEmpty;
  }

  String get prefix {
    return _prefix!;
  }
}