name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-app-windows:
    name: build-app-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Dart SDK AMD64
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.1
          architecture: x64

      - name: Build App AMD64
        run: dart .\bin\make.dart

      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build\


  build-app-linux:
    name: build-app-linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Dart SDK AMD64
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.1
          architecture: x64

      - name: Build App AMD64
        run: dart ./bin/make.dart

      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/


  build-app-macos:
    name: build-app-macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Dart SDK AMD64
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.1
          architecture: x64

      - name: Build App AMD64
        run: dart ./bin/make.dart

      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  release:
    name: Release App

    needs: [ build-app-windows, build-app-linux, build-app-macos ]
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true

      - name: Download the build result
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Release App
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*"
          name: DeltaZX_Authenticator Auto Release v${{ steps.tag.outputs.tag }}
          token: ${{ secrets.TOKEN }}

# 参考: https://www.bilibili.com/video/BV1uv4y1w7Yc/
